export const PHONE_CODES = [
  { dialCode: "+1",   iso: "US", flag: "🇺🇸", name: "United States" },
  { dialCode: "+1",   iso: "CA", flag: "🇨🇦", name: "Canada" },
  { dialCode: "+44",  iso: "GB", flag: "🇬🇧", name: "United Kingdom" },
  { dialCode: "+61",  iso: "AU", flag: "🇦🇺", name: "Australia" },
  { dialCode: "+64",  iso: "NZ", flag: "🇳🇿", name: "New Zealand" },
  { dialCode: "+33",  iso: "FR", flag: "🇫🇷", name: "France" },
  { dialCode: "+49",  iso: "DE", flag: "🇩🇪", name: "Germany" },
  { dialCode: "+39",  iso: "IT", flag: "🇮🇹", name: "Italy" },
  { dialCode: "+34",  iso: "ES", flag: "🇪🇸", name: "Spain" },
  { dialCode: "+31",  iso: "NL", flag: "🇳🇱", name: "Netherlands" },
  { dialCode: "+32",  iso: "BE", flag: "🇧🇪", name: "Belgium" },
  { dialCode: "+41",  iso: "CH", flag: "🇨🇭", name: "Switzerland" },
  { dialCode: "+43",  iso: "AT", flag: "🇦🇹", name: "Austria" },
  { dialCode: "+46",  iso: "SE", flag: "🇸🇪", name: "Sweden" },
  { dialCode: "+47",  iso: "NO", flag: "🇳🇴", name: "Norway" },
  { dialCode: "+45",  iso: "DK", flag: "🇩🇰", name: "Denmark" },
  { dialCode: "+358", iso: "FI", flag: "🇫🇮", name: "Finland" },
  { dialCode: "+48",  iso: "PL", flag: "🇵🇱", name: "Poland" },
  { dialCode: "+351", iso: "PT", flag: "🇵🇹", name: "Portugal" },
  { dialCode: "+7",   iso: "RU", flag: "🇷🇺", name: "Russia" },
  { dialCode: "+81",  iso: "JP", flag: "🇯🇵", name: "Japan" },
  { dialCode: "+82",  iso: "KR", flag: "🇰🇷", name: "South Korea" },
  { dialCode: "+86",  iso: "CN", flag: "🇨🇳", name: "China" },
  { dialCode: "+852", iso: "HK", flag: "🇭🇰", name: "Hong Kong" },
  { dialCode: "+886", iso: "TW", flag: "🇹🇼", name: "Taiwan" },
  { dialCode: "+65",  iso: "SG", flag: "🇸🇬", name: "Singapore" },
  { dialCode: "+60",  iso: "MY", flag: "🇲🇾", name: "Malaysia" },
  { dialCode: "+66",  iso: "TH", flag: "🇹🇭", name: "Thailand" },
  { dialCode: "+62",  iso: "ID", flag: "🇮🇩", name: "Indonesia" },
  { dialCode: "+63",  iso: "PH", flag: "🇵🇭", name: "Philippines" },
  { dialCode: "+84",  iso: "VN", flag: "🇻🇳", name: "Vietnam" },
  { dialCode: "+91",  iso: "IN", flag: "🇮🇳", name: "India" },
  { dialCode: "+92",  iso: "PK", flag: "🇵🇰", name: "Pakistan" },
  { dialCode: "+880", iso: "BD", flag: "🇧🇩", name: "Bangladesh" },
  { dialCode: "+94",  iso: "LK", flag: "🇱🇰", name: "Sri Lanka" },
  { dialCode: "+971", iso: "AE", flag: "🇦🇪", name: "UAE" },
  { dialCode: "+966", iso: "SA", flag: "🇸🇦", name: "Saudi Arabia" },
  { dialCode: "+965", iso: "KW", flag: "🇰🇼", name: "Kuwait" },
  { dialCode: "+974", iso: "QA", flag: "🇶🇦", name: "Qatar" },
  { dialCode: "+20",  iso: "EG", flag: "🇪🇬", name: "Egypt" },
  { dialCode: "+27",  iso: "ZA", flag: "🇿🇦", name: "South Africa" },
  { dialCode: "+234", iso: "NG", flag: "🇳🇬", name: "Nigeria" },
  { dialCode: "+254", iso: "KE", flag: "🇰🇪", name: "Kenya" },
  { dialCode: "+233", iso: "GH", flag: "🇬🇭", name: "Ghana" },
  { dialCode: "+55",  iso: "BR", flag: "🇧🇷", name: "Brazil" },
  { dialCode: "+52",  iso: "MX", flag: "🇲🇽", name: "Mexico" },
  { dialCode: "+54",  iso: "AR", flag: "🇦🇷", name: "Argentina" },
  { dialCode: "+56",  iso: "CL", flag: "🇨🇱", name: "Chile" },
  { dialCode: "+57",  iso: "CO", flag: "🇨🇴", name: "Colombia" },
] as const;

export type PhoneCode = typeof PHONE_CODES[number];
